packages:
  - next
  - strapi

catalog:
  "@strapi/strapi": 5.16.1
  "@strapi/plugin-cloud": 5.16.1
  "@strapi/plugin-users-permissions": 5.16.1
  "@strapi/types": 5.16.1
  "@strapi/typescript-utils": 5.16.1
  react: 18.3.1
  react-dom: 18.3.1
  react-router-dom: 6.30.0
  styled-components: 6.1.19
  typescript: 5.9.3

onlyBuiltDependencies:
  - "@swc/core"
  - "@codemirror/state"
  - core-js-pure
  - esbuild
  - sharp
link-workspace-packages: deep
